FUNCTION SENDMAIL(EMF,EMT,ETO,ECC,BCC,ESUBJECT,EFROM,EATTACH,EOPTS)
*
 IF UNASSIGNED(BCC) THEN BCC = ""
 IF UNASSIGNED(EMF) THEN EMF = ""
 IF UNASSIGNED(EMT) THEN EMT = ""
 IF UNASSIGNED(ECC) THEN ECC = ""
 IF UNASSIGNED(EFROM) THEN EFROM = ""
 IF UNASSIGNED(EATTACH) THEN EATTACH = ""
 IF UNASSIGNED(EATTACH) THEN EATTACH = ""
 IF UNASSIGNED(ESUBJECT) THEN ESUBJECT = ""
 *
 BLATPATH = "C:\TEMP\"
 *
 DEBUGON = 0
 CRLF = CHAR(13):CHAR(10)
 BLAT    = 'kBLAT '
 IF EMT = "" THEN
    BLAT<2> = '-bodyF ':EMF
   END ELSE
    BLAT<2> = '- -body ':DQUOTE(EMT)
 END
 BLAT<3> = '-to ':ETO
*********
 BUGSTART = TIME()
 BLATKEY  = DATE():".":TIME():".TXT"
 BLAT<-1> = "-debug -timestamp -log ":BLATPATH:BLATKEY
 IF EOPTS # ""    THEN BLAT<-1> = EOPTS
 IF ECC # ""      THEN BLAT<-1> = '-cc ':ECC
 IF BCC # ""      THEN BLAT<-1> = '-bcc ':BCC
 IF ESUBJECT = "" THEN BLAT<-1> = "-ss" ELSE BLAT<-1> = '-subject ':DQUOTE(ESUBJECT)
 IF EATTACH  # "" THEN BLAT<-1> = '-attach ':EATTACH
 IF EFROM # ""    THEN BLAT<-1> = '-f ':EFROM
*
 CONVERT @FM TO " " IN BLAT
 EXECUTE CHAR(255):BLAT SETTING RC CAPTURING BUNG
 BUGSTOP = TIME()
 IF RC<1> # 0  THEN
    OPENSEQ BLATPATH:BLATKEY TO BLATBUF ELSE DEBUG
    WRITESEQ CRLF:BLAT:CRLF:BUGSTART:CRLF:BUNG:CRLF:BUGSTOP APPEND ON BLATBUF ELSE
       NULL
    END
    OSCLOSE BLATBUF
   END ELSE
    OSDELETE BLATPATH:BLATKEY
 END
*
RETURN RC<1>
END